# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Parchment mappings (optional)
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
loader_version_range=[1,)

## Mod Properties
mod_id=jukebox_360
mod_name=Jukebox 360°
mod_license=MIT
mod_version=1.0.7
mod_group_id=com.macatmovie.jukebox360
mod_authors=macatmovie
mod_description=Prevents jukebox/note block sounds from going silent when you look away.
